### ISSUE TITLE
config window: doesn't work because it says you are using this extension already when you actually just deleted it.

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#11]
originally reported in #7 

> Lastly, the extensions button will sometimes bug out when you try to delete it and create a completely new folder with that same extension again. Basically, it will say you are using this extension already when you actually just deleted it.

I'll look into this. This will take some time

**Comment by spartandrew18** [comment]
> originally reported in #7
> 
> > Lastly, the extensions button will sometimes bug out when you try to delete it and create a completely new folder with that same extension again. Basically, it will say you are using this extension already when you actually just deleted it.
> 
> I'll look into this. This will take some time

![image](https://user-images.githubusercontent.com/66539077/100651383-5d70c980-3313-11eb-9dda-930de02146ae.png)
![image](https://user-images.githubusercontent.com/66539077/100651355-5053da80-3313-11eb-91e7-aedb84d1558f.png)

This might give you a clue as to where to look. I found a workaround by just deleting the word "epub" from the metadata file when it got stuck and it fixed the issue. It seems to me that the metadata file is not syncing properly with the config settings when you delete an extension.

**Comment by ijgnd** [comment]
Thanks for your investigation.

I just uploaded a new version of the add-on that should fix the false error message shown in the add-on config. Could you update your add-ons and restart anki and try it out again.

If the error still persists with the new version please open a new bug report. Thanks.
