### ISSUE TITLE
Link multiple files

### ISSUE THREAD

**Issue by sazam0** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#12]
How can I add multiple file links?
e.g. 1pdf + 1video, or 2pdfs .....

**Comment by ijgnd** [comment]
the latest version from ankiweb from today allows this:

- up to now you only had one field "external_source" and "external_page" (or however you named them in the add-on config). In the card templates window check my new/extended dialog that inserts the clickable hyperlink into the templates. You can now select which field to use for the source or page. So you can e.g. add a hyperlink for "external_source_2"/"external_page_2" (if you have these fields) and so on.
- In the add-on config you can enable an experimental feature, check the new ankiweb description.

I need users who test my changes. If you find a bug let me know. If you have a better wording for the manual pull requests are also welcome.

**Comment by sazam0** [comment]
Can you please give some screenshots? I am trying but could not figure it out. It would be helpful if you show an example for 1pdf + 1video. 
Use case:
I am watching lectures (mp4 files in mpv). I want to include the lecture, and its pdf slides in my note. [sound:*mp4] in a field runs the video every time I open the cards which I do not prefer and mp4 with video tag does not seem to work in Anki. Your code seems to solve the problem additionally let me choose the directory.

for your issue #14 in this case: I would like to add each file in a dedicated field. I think that resolves the problem for adding "____" in file names and any number of any type of files could be added not just pdf. could it be possible?

**Comment by ijgnd** [comment]
My add-on only allows to add links that are opened in external files.

So if you want to add a video put just `name_of_the_video.mp4` in the field. Not `[sound:...]`. This means you won't see the video inside of Anki. Then set e.g. vlc player to watch videos.

**Comment by sazam0** [comment]
Thank you for your reply. I am stuck when I am trying to create a field for video and one for pdf. I can not figure out how to assign the 2 separate field for video and pdf. As there is only one option for "field_for_filename".

**Comment by ijgnd** [comment]
maybe this is screencast is useful: https://github.com/ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program/blob/master/screenshots/open_linked_pdf__two_files.mp4?raw=true

the config dialog no longer fits the current capabilities. Maybe I should remove the global source_field/page config value from the config and instead only rely on my dialog in the card template window.

**Comment by sazam0** [comment]
Maybe I could not explain. I am working with pdf no problem, but I do not get the video part. I am attaching a video here, maybe this will help to explain the problem. 

https://user-images.githubusercontent.com/50360175/102817024-4469ae80-43cf-11eb-8f6a-8ca027098b8b.mp4

**Comment by ijgnd** [comment]
your video shows a bug in my add-on config dialog, also see #11. I'll fix this and upload a new version to ankiweb soon - maybe tonight, tomorrow.

**Comment by ijgnd** [comment]
Sorry for the delay. I've been pretty busy the last weeks. I just uploaded a new version of the add-on that should fix the false error message shown in the add-on config. Could you update your add-ons and restart anki and try it out again.

If the error still persists with the new version please open a new bug report. Thanks.
