### ISSUE TITLE
Audio doesn't load

### ISSUE THREAD

**Issue by michaelcward1996** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#16]
This could possibly just be just me not knowing how to use the program.
I'm trying to get the addon working with vlc and while it does pull up vlc, it doesn't seem to load the audio file. Perhaps there's something wrong with my pathing? 
![image](https://user-images.githubusercontent.com/33991266/110015503-c7b15580-7cd8-11eb-9601-cb8da76769a2.png)
this is what my html looks like. 
![image](https://user-images.githubusercontent.com/33991266/110015828-2e367380-7cd9-11eb-91e6-4b67c42ed067.png)

**Comment by ijgnd** [comment]
If the media player opens but no file is added to the playlist my add-on either doesn't get a file and position from your note or it doesn't pass those along to the external program.

To pass the filename and position you must fill out the bottom line (command parameters) in the config dialog which is empty in your screenshot. 

Add the following: `--start-time=PAGE PATH`, see [the source code for the defaults](https://github.com/ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program/blob/3a5a39a4250d7769af71622cd6c89f4a31bbc36b/src/default_settings_for_progs.py#L68).

General point: For media in the anki media folder usually the built_in mpv/mplayer media player must work (and should suffice?)

**Comment by vonnr** [comment]
The problem still persists, still no audio playing after clicking inserted vlc link. 
![image](https://user-images.githubusercontent.com/81969507/120493948-f7621d80-c3ed-11eb-8a35-dc8e162ed503.png)

**Comment by ijgnd** [comment]
could you update your add-ons and try again. Now it should work.

Background: the path separator on mac and linux is `/` whereas the default in windows is `\`. I mostly use a pdf viewer and my windows pdf viewer also handles `/` so I never noticed this problem in my add-on. The update should adjust the path separator on windows so that vlc actually finds the file.

**Comment by ijgnd** [comment]
let me know if this works for you.

**Comment by vonnr** [comment]
thanks, it worked.
