### ISSUE TITLE
Is it possible to open the link automatically?

### ISSUE THREAD

**Issue by 36jerry** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#2]
Is it possible to add an option to open the link automatically? The front is a word, and when the back shows, a webpage opens automatically.

**Comment by ijgnd** [comment]
I doubt that my add-on is relevant when you just want to open a link in your browser. Anki should have all you need.

I would google for something like "open page automatically javascript". maybe there's some javascript code that you can run. I don't really know js so I can't properly help with this. maybe try the anki user forum or subreddit.
