### ISSUE TITLE
My Anki don't create 'Ext-Docs-Link' button

### ISSUE THREAD

**Issue by jsjuris89** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#5]
I'm using Manjaro Linux.
**Anki version:** 
Version 2.1.26 (arch-linux-2.1.26-1)
Python 3.8.3 Qt 5.15.0 PyQt 5.15.0

---

I tried to type in manually that code but getting an error. Can you provide that code (maybe I mistyped something) or help me get that button to get created?

**Comment by ijgnd** [comment]
Could you show a screenshot of the "Card Types for ..." window? In the bottom bar there should be a button "Ext-Docs-Link". 

If you don't have this button: Many problems are caused by interference between add-ons. To rule these out: Disable all other add-ons and restart Anki. Do you now see the button?

Also: For Linux I only test with the binaries released on apps.ankiweb.net. 2.1.26 was bundled with Qt 5.14. So you seem to have a manjaro specific build. Sometimes these bring new problems, e.g. new Qt versions sometimes have bugs that need workarounds in the anki code. So if bundle a newer qt version with an older Anki version you'll get a different behavior than with the binary from ankiweb. So you might want to try an official build but I'm not sure how much this would help here.

I use the following (adjust the field names as needed).

```html

<br><br>
<a href='javascript:open_in_external_helper_function();'>View external file: {{text:external_source}}</a>
<script>
    function open_in_external_helper_function(){
        let mysource = String.raw`{{text:external_source}}`.replace(/\\/g, "\\\\");
        let mypage = "{{text:external_page}}";
        let mycmd = "open_external_files1994996371" + mysource + "1994996371" + mypage;
        pycmd(mycmd);
    }
</script>
```

**Comment by jsjuris89** [comment]
First, thanks for fast, detailed response!

Got the button now.
I did 2 things: installed more than 400 updates on my sytem and restarted Anki.
Checked version of Anki its the same. I think restarting Anki made the button appear.

---

But now I'm a little unsure how to proceed with step 3.
I guess "Populate fields.." is meant for Windows users. And I dont really understand what I should put in all those fields (especially first two):

- Default folder for relative paths
- Extensions
- command/program

I'm trying to open a .gif file. By default on my system that is being opened by GwenView. It would be wonderfull if you could assist me a litte how to get Anki open .gif files?

**Comment by ijgnd** [comment]
> I think restarting Anki made the button appear.

All Anki add-ons are only loaded after a restart.

&nbsp;

> I guess "Populate fields.." is meant for Windows users.

No. Why don't you click it and see what pdf viewers are suggested (which only works if you have evince or okular). Then you'll also see how the settings work.

&nbsp;

I haven't tried it but I guess I would try

    Default folder for relative paths: /home/MYUSER/Documents/PATH_WHERE_I_STORE_MY_GIFS
    Extensions: gif
    command/program: gwenview

If you have a gif `/home/MYUSER/Documents/PATH_WHERE_I_STORE_MY_GIFS/test.gif` with this config I would write `test.gif` into the `field_for_filename` (which you set in the add-on config).

**Comment by jsjuris89** [comment]
> All Anki add-ons are only loaded after a restart.

Ohh, I didn't know that.

![demo](https://i.ibb.co/CVVBXNn/Screenshot-20200818-220857.png)
Now it works. Got also to open video with VLC at specific time too. 

Thanks for help. Very useful addon. Trying to learn web development using Anki.

P.S. I'm curious, how long something like this take to you to make?
I checked your src folder you were using Pyton could this be made in NodeJS?

**Comment by ijgnd** [comment]
> could this be made in NodeJS?

My programming skills are very limited so take everything I write with a grain of salt. I don't think it would work. Anki is a python program so add-ons need be in python. There are some embedded webviews where you can (must) use js but these webviews deliberately run on a server that's isolated from the rest of the system. You could make paths accessible into the webviews (e.g. I do this in my other pdf add-on) but you'd still need python/pyqt to make a new dialog/window. And when it comes to the backend you also need python.

But if you know one programming language python shouldn't be too hard and as long as you don't want to do fancy stuff you can achieve a lot by just copying existing pyqt code. Maybe useful: https://www.reddit.com/r/Anki/comments/ctmwmn/fastest_and_easiest_way_to_grasp_python_for/
