### ISSUE TITLE
Open files that don't end in ".<ext>"

### ISSUE THREAD

**Issue by grooveboxunited** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#6]
I'm trying to get this add-on to open my [HTML notebook](https://tiddlywiki.com/) in Firefox (Windows 10).

It works great when the path is "folder\file.html", but if I want to open to a specific note the file path to open in the browser becomes "folder\file.html#note-name".

Since the path no longer ends in ".html", the add-on doesn't recognise it as a path that should be opened in the browser.

Is there anything that can be done to get this to work with file paths in this format?

Thanks for the great add-on.

**Comment by ijgnd** [comment]
I made some quick changes to seem to accomplish what you want.

Coud you help testing? [Download and install this file](https://github.com/ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program/releases/download/2020-11-13/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program__2020-11-13.ankiaddon).

video: [installing ankiaddon files from outside of ankiweb](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation.gif)

**Comment by grooveboxunited** [comment]
Wow yes that works thank you! That was very generous of you to make that fix, I really appreciate it.

**Comment by ijgnd** [comment]
If you notice a problem please let me know, e.g. reopen this issue or make a new one.

**Comment by ijgnd** [comment]
I just uploaded a new version of my add-on to ankiweb which you should soon get as an update. 

I made some changes, e.g. I wanted case insensitive matching  so that a file named "France.pdf" is found even if I put "france.pdf" into my note. The feature `Open files that don't end in ".<ext>"` should still work. But if I broke this by accident please let me know.

**Comment by grooveboxunited** [comment]
Yep it seems to still be working fine. Thanks.
