### ISSUE TITLE
EPUB Compatibility

### ISSUE THREAD

**Issue by spartandrew18** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#7]
I have no clue how to set this up for Calibre? Could you help me?

![image](https://user-images.githubusercontent.com/66539077/100555759-bb49d680-326b-11eb-8694-c8c9ef989005.png)

![image](https://user-images.githubusercontent.com/66539077/100555765-cef53d00-326b-11eb-8019-0c30a4d8fc37.png)

![image](https://user-images.githubusercontent.com/66539077/100555777-dae0ff00-326b-11eb-954a-c6e6c8e49699.png)

![image](https://user-images.githubusercontent.com/66539077/100555799-f8ae6400-326b-11eb-86f7-4d7284bbcedd.png)

I click and nothing happens

**Comment by ijgnd** [comment]
Thanks for reporting this bug. I updated the ankiweb listing.

- Update your add-ons.
- Before you try again adjust the config: Remove the "--detach" from the "command parameters to open on specific page" (bottom of your first and third picture). Apparently this was linux only.
- Restart Anki

Try again: Does it work now?

**Comment by spartandrew18** [comment]
![image](https://user-images.githubusercontent.com/66539077/100558899-564bac00-327e-11eb-9060-8db94a30891e.png)
![image](https://user-images.githubusercontent.com/66539077/100558937-8a26d180-327e-11eb-9bf1-b62c793adb9c.png)
![image](https://user-images.githubusercontent.com/66539077/100558908-65caf500-327e-11eb-8bb7-ab4f1cef69b6.png)
![image](https://user-images.githubusercontent.com/66539077/100558914-6f545d00-327e-11eb-817a-b0a7744ded8e.png)

Thank you so much it does seem to work now!

I have a couple more questions if you don't mind.

In Calibre I have the main library folder that holds all my epub and pdf files in their separate subfolders as you can see from the first picture. If I wanted to look for the biology book I would need to set the default folder/relative path to that specific biology subfolder with its epub or pdf file directed inside. My questions for you is there any way you can have the default folder/relative pathway search/cover multiple subfolders within the main folder. As of right now, I can only open one epub or one pdf because I cannot create another extension for each individual book, it will say its already being used up by another extension.

Also for the pdf files, it seems that Microsoft Edge (Chromium Edition) will not allow me to open a specific page on startup. I believe this may be a problem that is with Edge and not your addon. I looked online for some forums and some people were asking the same question.

Another thing is when you add the source file in the editor, it must include .pdf or .epub at the end of the file name. This shows up in the naming when the card is shown. Is there any way to hide this from showing when you look at the card?

Lastly, the extensions button will sometimes bug out when you try to delete it and create a completely new folder with that same extension again. Basically, it will say you are using this extension already when you actually just deleted it.

**Comment by ijgnd** [comment]
>  is there any way you can have the default folder/relative pathway search/cover multiple subfolders within the main folder.

see issue #9


> Microsoft Edge (Chromium Edition) 

see issue #8 

&nbsp;

> Another thing is when you add the source file in the editor, it must include .pdf or .epub at the end of the file name. This shows up in the naming when the card is shown. Is there any way to hide this from showing when you look at the card?

see issue #10


&nbsp;

> Basically, it will say you are using this extension already when you actually just deleted it.

that's a bug, see issue #11

**Comment by ijgnd** [comment]
I think it's best to continue the discussion in these topics. If you find another bug just make a new topic. If the epub problem returns just reopen this bug.
