### ISSUE TITLE
check multiple relative paths

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki__Open_linked_pdf-_docs-_epub-_audio-_video-_etc_in_external_Program#9]
originally asked in #7 

>  is there any way you can have the default folder/relative pathway search/cover multiple subfolders within the main folder.

Not at the moment. I just added this issue as a reminder. But who know's when it's finished.  What you can do now: 

- You can also put the full path into the Anki field - drag and drop the file from the Explorer into anki and you should have the path formatted in a way that my add-on understands it.
- in Windows you can make a file appear into multiple locations/folders (even though actually the file is only in one location), e.g. you can use a hardlink, see https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by spartandrew18** [comment]
> originally asked in #7
> 
> > is there any way you can have the default folder/relative pathway search/cover multiple subfolders within the main folder.
> 
> Not at the moment. I just added this issue as a reminder. But who know's when it's finished. What you can do now:
> 
> * You can also put the full path into the Anki field - drag and drop the file from the Explorer into anki and you should have the path formatted in a way that my add-on understands it.
> * in Windows you can make a file appear into multiple locations/folders (even though actually the file is only in one location), e.g. you can use a hardlink, see https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

![image](https://user-images.githubusercontent.com/66539077/100658426-08d24c00-331d-11eb-9544-150b9124efe1.png)
![image](https://user-images.githubusercontent.com/66539077/100658456-1687d180-331d-11eb-96f7-b7ba0d85bafc.png)
![image](https://user-images.githubusercontent.com/66539077/100658531-33bca000-331d-11eb-8d1d-e93fd5bb65e0.png)
![image](https://user-images.githubusercontent.com/66539077/100658545-3a4b1780-331d-11eb-8a3f-737320fa2de2.png)
![image](https://user-images.githubusercontent.com/66539077/100658567-47680680-331d-11eb-93bc-15ec9bc4e64f.png)
![image](https://user-images.githubusercontent.com/66539077/100658582-4e8f1480-331d-11eb-8295-e51ca704d9bd.png)
![image](https://user-images.githubusercontent.com/66539077/100658612-5cdd3080-331d-11eb-949b-e5873a13dbaf.png)

EPUBS seems to be opening fine. Any ideas as to why the PDF file location is different with the addon?

**Comment by ijgnd** [comment]
I just uploaded a new version of the add-on that prints the command that is run when you click a link my add-on created. You only see this if you run Anki from the cmd/command prompt: `C:\Program Files\Anki\anki-console.exe`. Then you see diagnostic messages and the command executed should be printed below the line `____Open linked pdf addon:___`. When run this command from the cmd: Does this work?

What's the command that is run? Does it work?

**Comment by ijgnd** [comment]
in general: msedge works for me.

**Comment by spartandrew18** [comment]
[15168] PyInstaller Bootloader 3.x
[15168] LOADER: executable is C:\Program Files\Anki\anki-console.exe
[15168] LOADER: homepath is C:\Program Files\Anki
[15168] LOADER: _MEIPASS2 is NULL
[15168] LOADER: archivename is C:\Program Files\Anki\anki-console.exe
[15168] LOADER: C:\Program Files\Anki\anki-console.exe contains a digital signature
[15168] LOADER: No need to extract files to run; setting extractionpath to homepath
[15168] LOADER: SetDllDirectory(C:\Program Files\Anki)
[15168] LOADER: Already in the child - running user's code.
[15168] LOADER: Python library: C:\Program Files\Anki\python38.dll
[15168] LOADER: Loaded functions from Python library.
[15168] LOADER: Manipulating environment (sys.path, sys.prefix)
[15168] LOADER: sys.prefix is C:\Program Files\Anki
[15168] LOADER: Pre-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
[15168] LOADER: Setting runtime options
[15168] LOADER: Initializing python
[15168] LOADER: Overriding Python's sys.path
[15168] LOADER: Post-init sys.path is C:\Program Files\Anki\base_library.zip;C:\Program Files\Anki
[15168] LOADER: Setting sys.argv
[15168] LOADER: setting sys._MEIPASS
[15168] LOADER: importing modules from CArchive
[15168] LOADER: extracted struct
[15168] LOADER: callfunction returned...
[15168] LOADER: extracted pyimod01_os_path
[15168] LOADER: callfunction returned...
[15168] LOADER: extracted pyimod02_archive
[15168] LOADER: callfunction returned...
[15168] LOADER: extracted pyimod03_importers
[15168] LOADER: callfunction returned...
[15168] LOADER: Installing PYZ archive with Python modules.
[15168] LOADER: PYZ archive: PYZ-00.pyz
[15168] LOADER: Running pyiboot01_bootstrap.py
[15168] LOADER: Running pyi_rth_win32comgenpy.py
[15168] LOADER: Running pyi_rth_multiprocessing.py
[15168] LOADER: Running pyi_rth_certifi.py
[15168] LOADER: Running pyi_rth_pyqt5.py
[15168] LOADER: Running pyi_rth_pkgres.py
[15168] LOADER: Running pyi_rth_pyqt5webengine.py
[15168] LOADER: Running runanki.py
mpv too old for key rebinding
deckDueTree() is deprecated; use decks.deck_tree() for a tree without counts, or sched.deck_due_tree()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
deckDueTree() is deprecated; use decks.deck_tree() for a tree without counts, or sched.deck_due_tree()
conf key imgocc should be fetched with col.get_config(), and saved with col.set_config()
conf key imgocc should be fetched with col.get_config(), and saved with col.set_config()
conf key imgocc should be fetched with col.get_config(), and saved with col.set_config()
deckDueTree() is deprecated; use decks.deck_tree() for a tree without counts, or sched.deck_due_tree()
deckDueTree() is deprecated; use decks.deck_tree() for a tree without counts, or sched.deck_due_tree()
stripSounds() deprecated
____Open linked pdf addon:___
"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" "file:///C:/Users/Andrew/Calibre Library/Anki EPUB-PDF Addon/Biology Textbook.pdf"
_____________________________

**Comment by ijgnd** [comment]
Run the last line you posted from your command prompt: Copy and paste it there and then press "Enter". 

Does this work?

**Comment by spartandrew18** [comment]
> Run the last line you posted from your command prompt: Copy and paste it there and then press "Enter".
> 
> Does this work?

![image](https://user-images.githubusercontent.com/66539077/100674517-4215b680-3333-11eb-8e15-e50c0f03e75a.png)

**Comment by ijgnd** [comment]
This says two things:

- the path for msedge is correct.
- There's something wrong about the file: 
    - Maybe you have the wrong path: To find out: Rename the file to "test.pdf" and move it home `C:\Users\Andrew\test.pdf`: This way you have no folders or filenames with spaces which can complicate things. When you run from cmd `"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"  C:\Users\Andrew\test.pdf`what happens?
    - Maybe the file is broken: But I guess you can open it when you drag and drop it directly into edge?
    - hardlinks are rarely used. Though usually they shouldn't cause problems and for me hardlinks in Windows work with my add-on.

**Comment by spartandrew18** [comment]
![image](https://user-images.githubusercontent.com/66539077/100675531-1f849d00-3335-11eb-8607-a39e0afa7e6c.png)
![image](https://user-images.githubusercontent.com/66539077/100675548-257a7e00-3335-11eb-9dd4-1f0ace1b7432.png)
![image](https://user-images.githubusercontent.com/66539077/100675558-2a3f3200-3335-11eb-8531-960e64c11472.png)
![image](https://user-images.githubusercontent.com/66539077/100675597-3f1bc580-3335-11eb-8435-6c5179ca67d1.png)

Double Clicking the file opens it correctly. Dragging the file to Edge Browser results in the picture above as well! IDK?

**Comment by spartandrew18** [comment]
Yep just copy-pasting the file and it works fine.

![image](https://user-images.githubusercontent.com/66539077/100676602-35935d00-3337-11eb-8c37-32093dc03208.png)

**Comment by ijgnd** [comment]
I'm glad you have at least something that works.

I have an idea: It seems that you created a "symbolic link"/"symlink" to the file. These don't work for me in msedge. Whereas "hardlinks" do work. If you make a "hardlink" does it work?

**Comment by spartandrew18** [comment]
> I'm glad you have at least something that works.
> 
> I have an idea: It seems that you created a "symbolic link"/"symlink" to the file. These don't work for me in msedge. Whereas "hardlinks" do work. If you make a "hardlink" does it work?

GREAT SUCCESS! I am sorry I made the rookie mistake of soft link instead of hard link file....

![image](https://user-images.githubusercontent.com/66539077/100678456-2dd5b780-333b-11eb-8bf5-de75b809710d.png)

**Comment by ijgnd** [comment]
Afaik it's this: hardlinks don't take up space. But they appear as regular files. So tools that just count the size of all files will count each instance of the file. This can be misleading. Other tools that directly check the unused space on a disk will not be "fooled". 

There might be other caveats. If you use some cloud sync software like dropbox who knows how it'll handle hardlinks. Who knows what your backup software makes of these ...

You'd have to google for more details.
